export enum ProviderName {
  OPENAI = 'openai',
  FLUX = 'flux',
  IDEOGRAM = 'ideogram',
}

export enum GenerationTaskType {
  GENERAL_AD_VISUAL = 'GENERAL_AD_VISUAL',
  PHOTOREALISTIC_AD = 'PHOTOREALISTIC_AD',
  PRODUCT_SHOT = 'PRODUCT_SHOT',
  LIFESTYLE_SCENE = 'LIFESTYLE_SCENE',
  POSTER_TEXT_HEAVY = 'POSTER_TEXT_HEAVY',
  LOGO_LIKE_TEXT_VISUAL = 'LOGO_LIKE_TEXT_VISUAL',
  SOCIAL_AD_SQUARE = 'SOCIAL_AD_SQUARE',
  STORY_VERTICAL = 'STORY_VERTICAL',
  IMAGE_EDIT = 'IMAGE_EDIT',
  BACKGROUND_REPLACE = 'BACKGROUND_REPLACE',
  MULTI_REFERENCE_EDIT = 'MULTI_REFERENCE_EDIT',
  PREMIUM_RENDER = 'PREMIUM_RENDER',
  QUICK_DRAFT = 'QUICK_DRAFT',
}

export enum ProviderHealthStatus {
  HEALTHY = 'HEALTHY',
  DEGRADED = 'DEGRADED',
  UNAVAILABLE = 'UNAVAILABLE',
  CIRCUIT_OPEN = 'CIRCUIT_OPEN',
  RECOVERING = 'RECOVERING',
}

export enum QualityModeEnum {
  DRAFT = 'DRAFT',
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
}

export enum TextRequirementMode {
  NONE = 'NONE',
  APPROXIMATE = 'APPROXIMATE',
  EXACT = 'EXACT',
}
